---
- name: Clone repository
  become: true
  git:
    repo: https://github.com/byt3bl33d3r/CrackMapExec
    dest: "{{ cme_git_location }}/crackmapexec"
    update: yes
    recursive: yes
  register: crackmapexec

- name: Install dependencies
  become: true
  when: ansible_os_family == "Debian" and crackmapexec.changed
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - libssl-dev
    - libffi-dev
    - python-dev
    - build-essential

- name: Install Python requirements
  when: crackmapexec.changed
  shell: pipenv install
  environment:
    PATH: "$HOME/.local/bin:{{ ansible_env.PATH }}"
  args:
    chdir: "{{ cme_git_location }}/crackmapexec"

- name: Install CrackMapExec
  when: crackmapexec.changed
  become: true
  become_flags: -E
  command: pipenv run python setup.py install
  args:
    chdir: "{{ cme_git_location }}/crackmapexec"
